[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0x0f14341A7f464320319025540E8Fe48Ad0fe5aec"
optimizer = true
optimizer_runs = 999999

fs_permissions = [
  { "access" = "read-write", "path" = "./script/output/"},
  { "access" = "read-write", "path" = "./deployments/" },
  { "access" = "read", "path" = "./script/input/"},
  { "access" = "read", "path" = "./broadcast/" },
  { "access" = "read", "path" = "./out/" },
]

[rpc_endpoints]
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
pangolin = "https://pangolin-rpc.darwinia.network"

[etherscan]
arbitrum-goerli = { key = "${ETHERSCAN_ARBITRUM_KEY}" }
pangolin = { key = "${ETHERSCAN_PANGOLIN_KEY}", url = "https://pangolin.api.subscan.io/api/scan/evm/contract/verifysource" }
